(incomplete) workaround: spawn a thread for Java method
Ref: https://issuetracker.google.com/issues/37035211#comment8

The thread above doesn't seem related to this but the comment gave me a hint

But the log reports another error:

```
[ERROR] ERR: panicked at 'called `Result::unwrap()` on an `Err` value: Error(ThreadDetached, State { next_error: None, backtrace: InternalBacktrace })', src/libcore/result.rs:1188:5
```

This error doesn't cause a crash of the app. But perhaps indicate a problem.